[package]
name = "kytes"
version = "0.1.0"
edition = "2021"
description = "Soaring in the Cloud, but you pull the strings."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
rand = "0.8.5"
z32 = "1.0.2"
