[package]
name = "mast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
redb = "1.4.0"
varu64 = "0.7.0"

[dev-dependencies]
proptest = "1.4.0"
tempfile = "3.8.1"
