[package]
name = "authn"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "signup"
path = "./authn/signup.rs"

[[bin]]
name = "authenticator"
path = "./authz/authenticator.rs"

[[bin]]
name = "request"
path = "./request/main.rs"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
clap = { version = "4.5.16", features = ["derive"] }
pubky = { path = "../pubky" }
pubky-common = { version = "0.1.0", path = "../pubky-common" }
reqwest = "0.12.8"
rpassword = "7.3.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
url = "2.5.2"
