[package]
name = "pubky-common"
version = "0.1.0"
edition = "2021"
description = "Types and struct in common between Pubky client and homeserver"
license = "MIT"
repository = "https://github.com/pubky/pubky-core"
categories = ["web-programming", "authentication", "cryptography"]
keywords = ["pkarr", "pubky", "auth", "pubkey"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.5.1"
blake3 = "1.5.5"
ed25519-dalek = { version = "2.1.1", features = ["serde"] }
once_cell = "1.20.3"
rand = "0.9.0"
thiserror = "2.0.11"
postcard = { version = "1.1.1", features = ["alloc"] }
crypto_secretbox = { version = "0.1.1", features = ["std"] }
argon2 = { version = "0.5.3", features = ["std"] }

pubky-timestamp = { version = "0.4.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
pkarr = { version = "3.1.1", default-features = false, features = ["keys"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.77"

[dev-dependencies]
postcard = "1.1.1"
