# Use testnet network (local DHT) for testing.
# testnet = false

# Secret key (in hex) to generate the Homeserver's Keypair
# secret_key = "0000000000000000000000000000000000000000000000000000000000000000"

# ICANN domain pointing to this server to allow browsers to connect to it.
# domain = "example.com"

# Port for the Homeserver to listen on.
port = 6287

# Storage directory Defaults to <System's Data Directory>
# storage = ""
